name: Build and Bundle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build for Linux
        run: cargo build --release

      - name: Prepare files
        run: |
          mkdir bundle
          cp target/release/godot-arch bundle/
          cp godot-arch.config.yaml bundle/

      - name: Create tar.gz archive
        run: tar -czvf godot-arch-linux.tar.gz -C bundle .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-arch-linux
          path: godot-arch-linux.tar.gz
          retention-days: 3

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build for Windows
        run: cargo build --release

      - name: Prepare files
        run: |
          mkdir bundle
          copy target\release\godot-arch.exe bundle\
          copy godot-arch.config.yaml bundle\

      - name: Create zip archive
        run: Compress-Archive -Path bundle\* -DestinationPath godot-arch-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-arch-windows
          path: godot-arch-windows.zip
          retention-days: 3
