name: Build and Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build for Linux
        run: cargo build --release

      - name: Prepare files
        run: |
          mkdir bundle
          cp target/release/godot-arch bundle/
          cp godot-arch.config.yaml bundle/

      - name: Create tar.gz archive
        run: tar -czvf godot-arch-linux.tar.gz -C bundle .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-arch-linux
          path: godot-arch-linux.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build for Windows
        run: cargo build --release

      - name: Prepare files
        run: |
          mkdir bundle
          copy target\release\godot-arch.exe bundle\
          copy godot-arch.config.yaml bundle\

      - name: Create zip archive
        run: Compress-Archive -Path bundle\* -DestinationPath godot-arch-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-arch-windows
          path: godot-arch-windows.zip
